server:
  port: "8080"
  host: "localhost"
  read_timeout: 30
  write_timeout: 30

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "cinema_epg"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

api:
  playlist_url: "https://pl.iptv2021.com/api/v4/playlist"
  epg_url: "https://pl.iptv2021.com/api/v4/epg"
  timeout: 30
  headers:
    Host: "pl.iptv2021.com"
    User-Agent: "Mozilla/5.0 (Linux; Android 11; SM-A127F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/137.0.7151.115 Mobile Safari/537.36"
    x-lhd-agent: '{"platform":"android","app":"limehd.ru.lite","version_name":"4.3.4","version_code":"529","sdk":30,"name":"Samsung+Galaxy+A12","device_id":"4b1c781b1d127ee5","is_huawei":0}'

logging:
  level: "info"
  format: "json"
