version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cinema_epg_postgres
    environment:
      POSTGRES_DB: cinema_epg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: cinema_epg_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: cinema_epg_app
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./config.docker.yaml:/root/config.yaml
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
